console.log("be name khoda")
console.log("ma seyed ali emami hastam")
console.log("salam")
console.log("khoby?")
console.log("baraye che mano negah mi koni?")
console.log("bi kari ke code man ro mibini?")
console.log(" ")
console.log(" ")
console.log(" ")
console.log(" ")
console.log(" ")
console.log("hanoz ham dari negah mi koni")
console.log(":/")
console.log(":|")
console.log("aqa base negah nacon ")
